config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :users
  root 'books#top'
  get 'home/about'  => 'books#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :introduction, length: { maximum: 50 }
  validates :name, length: { maximum: 20 }
  validates :name, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


	def after_sign_in_path_for(resource)
		user_path(current_user)
	end
	def after_sign_out_path_for(resource)
		root_path
	end

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])

	end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, except: [:about,:top]
	before_action :correct_user, only: [:edit,:update]
	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "You have creatad book successfully."
			redirect_to book_path(@book.id)
		else
			@post_book = Book.all
			render :index
		end
	end

	def index
		@book = Book.new
		@post_book =Book.all
	end
	def show
		@post_book = Book.find(params[:id])
	end
	def edit
		@edit_book = Book.find(params[:id])
	end
	def update
		@edit_book = Book.find(params[:id])
		if @edit_book.update(book_params)
		flash[:notice] = "You have updated user successfully."
		redirect_to book_path(@edit_book.id)
		else
		render :edit
		end


	end
	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	def about
	end

	private
	def book_params
		params.require(:book).permit(:title,:body)
	end
	def correct_user
		edit_book = Book.find(params[:id])
		if edit_book.user.id != current_user.id
		redirect_to books_path
	    end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit,:update]
	def index
		@user_all = User.all
	end
	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		  flash[:notice] = "You have updated user successfully."
		redirect_to user_path
		else
			render :edit
		end
	end
	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end
	def correct_user
		user = User.find(params[:id])
	 if user.id != current_user.id
	 	redirect_to user_path(current_user.id)
	 end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-xs-3">
<h2>Use info</h2>
<div class="profile-container">
	<%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "profile-thumb", fallback: "no_image.jpg" %>
 <table class="table table-striped">
  <tr>
  	<th>Name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
  	<th>Introduction</th>
	<th><%= user.introduction %></th>
  </tr>
 </table>

	<div class="row">
	<%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
  	
   </div>

<h2>New Book</h2>
<%= form_for(Book.new) do |f| %>
  <div class="row">
	<h4>Title</h4>
	<%= f.text_field :title , class: "col-xs-12" %>

	<h4>Opinion</h4>
	<%= f.text_area :body , class: "col-xs-12" %><br>

	<%= f.submit'Create Book',class: "create-book col-xs-12 btn btn-primary" %>
   </div>
<% end %>

		</div>
</div>

app/views/books/about.html.erb
<div class="about-m">welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</div>

app/views/books/edit.html.erb
<% if @edit_book.errors.any? %>
  <div class="alert alert-warning">
  	<%= @edit_book.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @edit_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h2>Editing Book</h2>
<%= form_for(@edit_book) do |f| %>

	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Opinion</h4>
	<%= f.text_area :body %>

	<%= f.submit'Update Book' %>
<% end %>

<%= link_to 'Show', book_path(@edit_book) %>
|
<%= link_to 'Back', '/books' %>

app/views/books/index.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<% if @book.errors.any? %>
  <div class="alert alert-warning">
  	<%= @book.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'books/list', user: current_user  %>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table">
  <thead>
  	<tr>
      <th></th>
  		<th>Title</th>
  		<th>Opinion</th>
  		<th colspan="3"></th>
  	</tr>
  </thead>
  <tbody>

    <% @post_book.each do |book| %>
     <tr>
     	<td><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, class: "profile-thumb", fallback: "no_image.jpg" %></td>
    	<td><%=link_to book.title, book_path(book.id) %></td>
    	<td><%= book.body %></td>
     </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <div class="flash">
       <%= flash[:notice] %>
     </div>
   <% end %>

<%= render 'books/list', user: @post_book.user  %>
<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table">
<tbody>
<tr>
	<td style="width: 60px"><%= attachment_image_tag @post_book.user, :profile_image, :fill, 60, 60, class: "profile-thumb", fallback: "no_image.jpg" %><%=link_to @post_book.user.name, user_path(@post_book.user.id) %></td>
	<td><%= @post_book.title %></td>
	<td><%= @post_book.body %></td>

	<% if @post_book.id == current_user.id %>
	<td><%= link_to "Edit", edit_book_path(@post_book),class: "btn btn-success" %></td>
	<td><%= link_to "Destroy", book_path(@post_book), class: "btn btn-danger" , method: :delete, "data-confirm" => "本当に消しますか？" %></td>
	<% end %>

</tr>
</tbody>
</table>
</div>

<!-- 編集部分 -->

app/views/books/top.html.erb
<% if flash[:notice] %>
     <div class="flash">
       <%= flash[:notice] %>
     </div>
   <% end %>
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md6-">
	welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!<br>
	in<span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,<br>
	you can share and exchange your opinions,inpressions,and emotions<br>
	about varioius books
<div class="row"><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></div>
<div class="row"><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-fixed-top">
                  <h2 class="main-title" style = "float: left">Bookers</h2>
                    <ul class="nav navbar-nav navbar-right">
                       <% if user_signed_in? %>

                            <li><%= link_to user_path(current_user) do %>
                              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
                            <% end %></li>

                            <li><%= link_to users_path do %>
                              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>Users
                            <% end %></li>

                            <li><%= link_to '/books' do %>
                              <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Books
                            <% end %></li>

                            <li><%= link_to destroy_user_session_path, method: :delete do %>
                              <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>logout
                            <% end %></li>

                      <% else %>

                           <li><%= link_to root_path do %>
                              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
                           <% end %></li>

                           <li><%= link_to '/home/about' do %>
                            <span class="glyphicon glyphicon-link" aria-hidden="true"></span>About
                            <% end %></li>

                           <li><%= link_to new_user_session_path do %>
                              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>log in
                            <% end %></li>

                           <li><%= link_to new_user_registration_path do %>
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>sign up
                            <% end %></li>

                       <% end %>
                    </ul>
          </nav>
    </header>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  <footer>
    CopyRight Infratop.inc
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-warning">
  	<%= @user.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h2>User Info</h2>
<%= form_for(@user) do |f| %>
	<label class="control-label" for="inputName">Name</label>
	<%= f.text_field :name,autofocus:true,id:"inputName" %>

	<div class="user-edit-image"></div>

	<label class="control-label" for="inputImage">Image</label>
	<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>

	<label class="control-label" for ="inputIntro">Introduction</label>
	<%= f.text_area :introduction,autofocus:true, class: "",id:"inputIntro" %><br>
    <%= f.submit "Update User", class:"btn btn-default" %>
 <% end %>

app/views/users/index.html.erb
<%= render 'books/list', user: current_user  %>
<div class="col-xs-9">
<h2>Users</h2>
<table class="table">
   <thead>
	<tr>
		<th>image</th>
		<th>name</th>
		<th colspan="3"></th>
	</tr>
   </thead>
	<tbody>
		<% @user_all.each do |userall| %>
		<tr>
		<td><%= attachment_image_tag userall, :profile_image, :fill, 60, 60, class: "profile-thumb", fallback: "no_image.jpg" %></td>
		<td><%= userall.name %></td>
		<td><%= link_to "Show",user_path(userall) %></td>
	   </tr>
	<% end %>
	</tbody>
</table>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<%= render 'books/list', user: @user  %>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table">
   <tr>
   	<td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "profile-thumb", fallback: "no_image.jpg" %></td>
	<td class="u-s-title">Title</td>
	<td  class="u-s-opi">Opinion</td>
   </tr>

<% @user.books.each do |book| %>
	 <tr>
	 	<td><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, class: "profile-thumb", fallback: "no_image.jpg" %></td>
		<td><%=link_to book.title, book_path(book.id) %></td>
		<td><%= book.body %></td>
	 </tr>
<% end %>
</table>
</div>